backend:
  name: git-gateway
  branch: main

media_folder: "/Principales2"
public_folder: "/Principales2"

collections:
  - name: "carrusel"
    label: "Carrusel"
    files:
      - label: "Imágenes del Carrusel"
        name: "imagenes"
        file: "static/carousel.json"
        fields:
          - label: "Imágenes"
            name: "imagenes"
            widget: "list"
            fields:
              - { label: "Imagen", name: "imagen", widget: "image" }
              - { label: "Texto alternativo", name: "alt", widget: "string" }