backend:
  name: git-gateway
  branch: main

media_folder: "principales2"
public_folder: "/principales2"

collections:
  - name: "carrusel"
    label: "Carrusel"
    folder: "principales2"
    create: true
    slug: "imagen-{{slug}}"
    fields:
      - label: "Imagen"
        name: "imagen"
        widget: "image"
      - label: "Texto alternativo"
        name: "alt"
        widget: "string"
        default: "Imagen del carrusel"